# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(parent=Form)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.radioButton.toggled.connect(self.radio_selected)
        self.radioButton_2.toggled.connect(self.radio_selected)
        self.radioButton_3.toggled.connect(self.radio_selected)
        self.radioButton_4.toggled.connect(self.radio_selected)
        self.radioButton_5.toggled.connect(self.radio_selected)
        #هر بار وضعیت (تغییر) یکی از دکمه‌های رادیویی تغییر کرد، تابع فراخوانی شود

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "سن:"))
        self.radioButton_4.setText(_translate("Form", "20"))
        self.radioButton_3.setText(_translate("Form", "21"))
        self.radioButton_5.setText(_translate("Form", "22"))
        self.label.setText(_translate("Form", "جنسیت:"))
        self.radioButton.setText(_translate("Form", "مرد"))
        self.radioButton_2.setText(_translate("Form", "زن"))
    def radio_selected(self):
        label=""
        if self.radioButton.isChecked():
             label="جنسیت شما مرد"
        elif self.radioButton_2.isChecked():
             label="جنسیت شما زن" 
        elif self.radioButton_3.isChecked():
             label="سن شما" + self.radioButton_3.text() 
        elif self.radioButton_4.isChecked():
             label="سن شما" + self.radioButton_4.text() 
        elif self.radioButton_5.isChecked():
             label="سن شما" + self.radioButton_5.text()
        self.label_3.setText(label)                      

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
